Objective

Deploy Sysmon on a Windows endpoint to capture system and network telemetry.

Environment

Host: Windows PC
Virtualization: VirtualBox
Victim Machine: Windows 11

Logging Tool: Sysmon

Steps
1. Installed Sysmon
2. Applied SwiftOnSecurity Sysmon configuration
3. Generated network traffic using curl
4. Investigated Event ID 3 network connection logs in Event Viewer

Findings
Sysmon successfully captured network connection telemetry generated by the curl command.

Relevant Event:
Event ID 3 – Network Connection
